version: 0.2

phases:
  build:
    commands:
      - IMAGE_URI=762233754891.dkr.ecr.us-east-1.amazonaws.com/testapp:latest
      - echo '[{"name":"your-container-name","imageUri":"'"$IMAGE_URI"'"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
