version: 0.2

env:
  variables:
    IMAGE_NAME: testapp
    AWS_REGION: us-east-1
    ECR_URI: 762233754891.dkr.ecr.us-east-1.amazonaws.com/testapp

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Image tag is $IMAGE_TAG

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME:latest $ECR_URI/$IMAGE_NAME:latest
      - docker tag $IMAGE_NAME:latest $ECR_URI/$IMAGE_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_URI/$IMAGE_NAME:latest
      - docker push $ECR_URI/$IMAGE_NAME:$IMAGE_TAG
      - echo Build completed successfully.

artifacts:
  files: '**/*'
